/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.*;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.*;

/**
 *
 * @author PC
 */
public class QuanLy extends javax.swing.JFrame {

    /**
     * Creates new form QuanLy
     */
    public static final String fileNhanVien = "NV.TXT", filePhongBan = "PB.TXT", fileChamCong = "CC.TXT";
    ArrayList<NhanVien> listNhanVien;
    ArrayList<PhongBan> listPhongBan;
    ArrayList<ChamCong> listChamCong;
    DefaultTableModel tableNhanVien, tablePhongBan, tableChamCong;
    public QuanLy() {
        initComponents();
        listNhanVien = new ArrayList<>();
        listPhongBan = new ArrayList<>();
        listChamCong = new ArrayList<>();
        tableNhanVien = (DefaultTableModel)jTable1.getModel();
        tablePhongBan = (DefaultTableModel)jTable2.getModel();
        tableChamCong = (DefaultTableModel)jTable3.getModel();
        loadDataToTable();
        loadDataToBox();
        saveDataToFile(saveNhanVien, listNhanVien, fileNhanVien);
        saveDataToFile(savePhongBan, listPhongBan, filePhongBan);
        saveDataToFile(saveChamCong, listChamCong, fileChamCong);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        getName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        getAddress = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        getPhone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        getWage = new javax.swing.JComboBox<>();
        addNhanVien = new javax.swing.JButton();
        saveNhanVien = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        getNamePhongBan = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        getDescript = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        addPhongBan = new javax.swing.JButton();
        savePhongBan = new javax.swing.JButton();
        getCoefficient = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        getWorkDays = new javax.swing.JTextField();
        addChamCong = new javax.swing.JButton();
        saveChamCong = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        conditionToSort = new javax.swing.JComboBox<>();
        sortByBox = new javax.swing.JButton();
        getIdNV = new javax.swing.JComboBox<>();
        getIdPB = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Ho Ten");

        jLabel3.setText("Dia Chi");

        jLabel4.setText("So dien thoai");

        jLabel5.setText("Bac luong");

        getWage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        addNhanVien.setText("Them");
        addNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNhanVienActionPerformed(evt);
            }
        });

        saveNhanVien.setText("Luu");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ma nv", "Ho ten", "Dia chi", "So dien thoai", "Bac luong"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(addNhanVien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveNhanVien))
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(getName)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getAddress)
                    .addComponent(getPhone)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(getWage, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(getName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(getAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(getPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(getWage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addNhanVien)
                    .addComponent(saveNhanVien))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Nhan Vien", jPanel1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ma phong", "Ten phong", "Mo ta", "He so cong viec"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel7.setText("Ten Phong");

        jLabel8.setText("Mo ta");

        jLabel10.setText("He so cong viec");

        addPhongBan.setText("Them");
        addPhongBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPhongBanActionPerformed(evt);
            }
        });

        savePhongBan.setText("Luu");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(addPhongBan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(savePhongBan))
                    .addComponent(jLabel7)
                    .addComponent(getNamePhongBan)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getDescript)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(getCoefficient))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(getNamePhongBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(getDescript, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(getCoefficient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addPhongBan)
                    .addComponent(savePhongBan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Phong Ban", jPanel2);

        jLabel13.setText("Ma nhan vien");

        jLabel14.setText("Ma phong");

        jLabel19.setText("So ngay lam");

        addChamCong.setText("Them");
        addChamCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addChamCongActionPerformed(evt);
            }
        });

        saveChamCong.setText("Luu");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ma nv", "Ho ten", "Ma phong", "Ten phong", "So ngay lam"
            }
        ));
        jScrollPane5.setViewportView(jTable3);

        conditionToSort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "theo ten nhan vien", "theo ten phong ban" }));

        sortByBox.setText("Sap xep");
        sortByBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortByBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(addChamCong)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(saveChamCong))
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(getWorkDays)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conditionToSort, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sortByBox)
                    .addComponent(getIdNV, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(getIdPB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(getIdNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(getIdPB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(getWorkDays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(conditionToSort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sortByBox)
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addChamCong)
                    .addComponent(saveChamCong))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cham Cong", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sortByBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortByBoxActionPerformed
        // TODO add your handling code here:
        String choice = conditionToSort.getItemAt(conditionToSort.getSelectedIndex());
        if (choice.equals("theo ten nhan vien")) {
            Collections.sort(listChamCong, (o1, o2) -> {
                return o1.getNhanVien().getName().compareTo(o2.getNhanVien().getName());
            });
        } else {
            Collections.sort(listChamCong, (o1, o2) -> {
                return o1.getPhongBan().getName().compareTo(o2.getPhongBan().getName());
            });
        }
    }//GEN-LAST:event_sortByBoxActionPerformed

    private void addChamCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addChamCongActionPerformed
        // TODO add your handling code here:
        int indexNhanVien = getIdNV.getSelectedIndex();
        int indexPhongBan = getIdPB.getSelectedIndex();
        NhanVien nhanVien = listNhanVien.get(indexNhanVien);
        PhongBan phongBan = listPhongBan.get(indexPhongBan);
        try {
            int workDays = Integer.parseInt(getWorkDays.getText());
            if (workDays < 0 || workDays > 30) {
                JOptionPane.showMessageDialog(null, "nhap sai so ngay lam");
            }
            ChamCong chamCong = new ChamCong(nhanVien, phongBan, workDays);
            int count = 0;
            for (ChamCong cc:listChamCong) {
                if (chamCong.trungNhau(cc)) {
                    int x = workDays + cc.getWorkDays();
                    if (x > 30) {
                        JOptionPane.showMessageDialog(null, "so ngay lam k duoc vuot qua 30");
                        return;
                    } else {
                        cc.setWorkDays(x);
                        tableChamCong.setValueAt(x, count, 4);
                        return;
                    }
                }
                count++;
                if (chamCong.dieuKien(cc)) {
                    JOptionPane.showMessageDialog(null, "1 nhan vien khong the lam 2 phong khac nhau");
                    return;
                }
            }
            tableChamCong.addRow(chamCong.toObjects());
            listChamCong.add(chamCong);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "So ngay lam phai nhap bang so");
        }
    }//GEN-LAST:event_addChamCongActionPerformed

    private void addPhongBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPhongBanActionPerformed
        // TODO add your handling code here:
        String name = getNamePhongBan.getText();
        String descript = getDescript.getText();
        String coefficient = getCoefficient.getText();

        int temp = listPhongBan.size() - 1;
        if (temp != -1) {
            PhongBan.setCurrentId(listPhongBan.get(temp).getId());
        }

        try {
            double h = Double.parseDouble(coefficient);
            PhongBan phongBan = new PhongBan(name, descript, h);
            for (PhongBan pb:listPhongBan) {
                if (phongBan.trungNhau(pb)) {
                    throw new trungNhauException();
                }
            }
            tablePhongBan.addRow(phongBan.toObjects());
            listPhongBan.add(phongBan);
            loadDataToBox();
        } catch (deTrongException e) {
            JOptionPane.showMessageDialog(null, "khong duoc de trong");
        } catch (heSoCongViecException e) {
            JOptionPane.showMessageDialog(null, "Nhap sai he so cong viec");
        } catch (trungNhauException e) {
            JOptionPane.showMessageDialog(null, "trung phong ban");
        }
    }//GEN-LAST:event_addPhongBanActionPerformed

    private void addNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNhanVienActionPerformed
        // TODO add your handling code here:
        try {
            String name = getName.getText();
            String address = getAddress.getText();
            String phone = getPhone.getText();
            int wage = getWage.getSelectedIndex() + 1;

            int temp = listNhanVien.size() - 1;
            if (temp != -1) {
                NhanVien.setCurrentId(listNhanVien.get(temp).getId());
            }

            NhanVien nhanVien = new NhanVien(name, address, phone, wage);
            for (NhanVien nv:listNhanVien) {
                if (nhanVien.trungNhau(nv)) {
                    throw new trungNhauException();
                }
            }
            tableNhanVien.addRow(nhanVien.toObjects());
            listNhanVien.add(nhanVien);
            loadDataToBox();
        } catch (deTrongException ex) {
            JOptionPane.showMessageDialog(null, "khong duoc de trong");
        } catch (hoTenException ex) {
            JOptionPane.showMessageDialog(null, "ho ten phai day du");
        } catch (soDienThoaiException ex) {
            JOptionPane.showMessageDialog(null, "so dien thoai sai");
        } catch (trungNhauException ex) {
            JOptionPane.showMessageDialog(null, "trung nhan vien");
        }
    }//GEN-LAST:event_addNhanVienActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addChamCong;
    private javax.swing.JButton addNhanVien;
    private javax.swing.JButton addPhongBan;
    private javax.swing.JComboBox<String> conditionToSort;
    private javax.swing.JTextField getAddress;
    private javax.swing.JTextField getCoefficient;
    private javax.swing.JTextField getDescript;
    private javax.swing.JComboBox<String> getIdNV;
    private javax.swing.JComboBox<String> getIdPB;
    private javax.swing.JTextField getName;
    private javax.swing.JTextField getNamePhongBan;
    private javax.swing.JTextField getPhone;
    private javax.swing.JComboBox<String> getWage;
    private javax.swing.JTextField getWorkDays;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JButton saveChamCong;
    private javax.swing.JButton saveNhanVien;
    private javax.swing.JButton savePhongBan;
    private javax.swing.JButton sortByBox;
    // End of variables declaration//GEN-END:variables

    private void loadDataToTable() {
        FileIO.readFile(listNhanVien, fileNhanVien);
        FileIO.readFile(listPhongBan, filePhongBan);
        FileIO.readFile(listChamCong, fileChamCong);
        for (NhanVien nhanVien:listNhanVien) {
            tableNhanVien.addRow(nhanVien.toObjects());
        }
        for (PhongBan phongBan:listPhongBan) {
            tablePhongBan.addRow(phongBan.toObjects());
        }
        for (ChamCong chamCong:listChamCong) {
            tableChamCong.addRow(chamCong.toObjects());
        }
    }
    
    private void loadDataToBox() {
        getIdNV.removeAllItems();
        getIdPB.removeAllItems();
        for (NhanVien nhanVien:listNhanVien) {
            getIdNV.addItem(nhanVien.getId()+"");
        }
        for (PhongBan phongBan:listPhongBan) {
            getIdPB.addItem(phongBan.getId()+"");
        }
    }
    
    private void saveDataToFile(JButton jb, ArrayList list, String file) {
        jb.addActionListener((e) -> {
            FileIO.writeFile(list, file);
            JOptionPane.showMessageDialog(null, "Da luu vao "+file);
        });
    }
}
